language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"


before_install:
 - sudo apt-get install -qq python-numpy python-scipy
 
# command to install dependencies
virtualenv:
  system_site_packages: true
  
  
# command to run tests
script: make test
